# Generated by Django 6.0.1 on 2026-02-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cost',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Article', 'Article/Documentation'), ('Course', 'Course')], default='Article', max_length=20),
        ),
    ]
