# Generated by Django 6.0.2 on 2026-02-22 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(max_length=10)),
                ('color_hex', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('CREATIVE', 'Creative'), ('INTEREST', 'Interest'), ('WORKSTYLE', 'Work Style'), ('CAREER', 'Career')], max_length=20)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceDomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_scores', to='quiz.domain')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='quiz.quizchoice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('choice', 'domain'), name='unique_choice_domain')],
            },
        ),
    ]
