# Generated by Django 6.0.2 on 2026-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video'), ('ARTICLE', 'Article'), ('COURSE', 'Course'), ('BOOK', 'Book'), ('INTERACTIVE', 'Interactive'), ('PROJECT', 'Project')], max_length=20)),
                ('platform', models.CharField(max_length=100)),
                ('is_free', models.BooleanField()),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
